version: "3.9"

services:
  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: mailhog
    ports:
      - "8025:8025"
    networks:
      - medium-api

  postgres:
    build:
      context: .
      dockerfile: ./docker/local/postgres/Dockerfile

    volumes:
      - local_postgres_db:/var/lib/postgresql/data
      - local_postgres_db_backups:/db_backups
    env_file:
      - ./.envs/.local/.postgres
    networks:
      - medium-api

  api:
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    volumes:
      - ./core:/app/core:z
      - ./local:/app/local:z
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    ports:
      - "8000:8000"
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    depends_on:
      - postgres
      - mailhog
    command: /start
    networks:
      - medium-api

networks:
  medium-api:
    driver: bridge

volumes:
  static_volume:
  media_volume:
  local_postgres_db: {}
  local_postgres_db_backups: {}
