name: PR

on:
  pull_request:
    types: [opened, synchronize]

  push:
    branches:
      - main


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      
      - name: Install pre-commit
        run: |
          pip install pre-commit
    
      - name: Run lint ci
        run: |
          /bin/bash -x run lint:ci
  
  test:
    runs-on: ubuntu-latest
    environment: TEST
    env:

      DATABASE_URL: postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@${{  vars.POSTGRES_HOST }}:${{ vars.POSTGRES_PORT }}/${{ vars.POSTGRES_DB }}
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      JWT_SIGNING_KEY: ${{ secrets.JWT_SIGNING_KEY }}
      CELERY_BROKER: ${{ vars.CELERY_BROKER }}
      IN_GITHUB: true

    services:
      postgres:
        image: postgres:15-bullseye
        env:
          POSTGRES_HOST: ${{ vars.POSTGRES_HOST  }}
          POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}
          POSTGRES_DB: ${{ vars.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 10s
          --health-retries 5
      es:
        image: elasticsearch:8.17.0
        env:
          discovery.type: single-node
          xpack.security.enabled: false      
        ports: 
          - "9200:9200"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install --upgrade pip && pip install poetry
          poetry config virtualenvs.in-project true
          poetry install --no-root

      - name: Run tests
        run: |
          /bin/bash -x run test:ci

         
